prefix:
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  geo: http://www.opengis.net/ont/geosparql#
  adms: http://www.w3.org/ns/adms#
  dbo : http://dbpedia.org/ontology/
  eurovoc: http://eurovoc.europa.eu/
  skos: http://www.w3.org/2004/02/skos/core#
  locn: http://www.w3.org/ns/locn#
  dct: http://purl.org/dc/terms/
  xsd: http://www.w3.org/2001/XMLSchema#
  dc: http://purl.org/dc/elements/1.1/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  cpsv: http://purl.org/vocab/cpsv#
  m8g: http://data.europa.eu/m8g/
  frbr: http://purl.org/vocab/frbr/core#
  owl: http://www.w3.org/2002/07/owl#

